package org.chingo.gutcom.domain;

// Generated Apr 14, 2013 10:15:06 PM by Hibernate Tools 4.0.0

/**
 * CommonFilterWord generated by hbm2java
 */
public class CommonFilterWord implements java.io.Serializable
{
	private String word; // rowKey，关键词
	private byte level; // 过滤级别

	public CommonFilterWord()
	{
	}

	public CommonFilterWord(String word, byte level)
	{
		this.word = word;
		this.level = level;
	}

	public String getWord()
	{
		return this.word;
	}

	public void setWord(String word)
	{
		this.word = word;
	}

	public byte getLevel()
	{
		return this.level;
	}

	public void setLevel(byte level)
	{
		this.level = level;
	}

}
