package org.chingo.gutcom.domain;

import org.apache.hadoop.hbase.client.Result;
import org.apache.hadoop.hbase.util.Bytes;

// Generated Apr 14, 2013 10:15:06 PM by Hibernate Tools 4.0.0

/**
 * CommonMsgRecv generated by hbm2java
 */
public class CommonMsgRecv implements java.io.Serializable
{

	private String mid; // rowKey，消息ID
	private String recvuserId; // 接收用户ID
	private String senduserId; // 发送用户ID
	private CommonUser recvuser; // 接收用户对象
	private CommonUser senduser; // 发送用户对象
	private String content; // 消息内容
	private long dateline; // 接收时间戳
	private byte isread; // 是否已读

	public CommonMsgRecv()
	{
	}

	public CommonMsgRecv(String mid, String recvuserId,
			String senduserId, String content, long dateline,
			byte isread)
	{
		this.mid = mid;
		this.recvuserId = recvuserId;
		this.senduserId = senduserId;
		this.content = content;
		this.dateline = dateline;
		this.isread = isread;
	}

	public String getMid()
	{
		return this.mid;
	}

	public String getContent()
	{
		return this.content;
	}

	public void setContent(String content)
	{
		this.content = content;
	}

	public long getDateline()
	{
		return this.dateline;
	}

	public void setDateline(long dateline)
	{
		this.dateline = dateline;
	}

	public byte getIsread()
	{
		return this.isread;
	}

	public void setIsread(byte isread)
	{
		this.isread = isread;
	}

	public String getRecvuserId()
	{
		return recvuserId;
	}

	public void setRecvuserId(String recvuserId)
	{
		this.recvuserId = recvuserId;
	}

	public String getSenduserId()
	{
		return senduserId;
	}

	public void setSenduserId(String senduserId)
	{
		this.senduserId = senduserId;
	}

	public CommonUser getRecvuser()
	{
		return recvuser;
	}

	public void setRecvuser(CommonUser recvuser)
	{
		this.recvuser = recvuser;
	}

	public CommonUser getSenduser()
	{
		return senduser;
	}

	public void setSenduser(CommonUser senduser)
	{
		this.senduser = senduser;
	}

	public void setMid(String mid)
	{
		this.mid = mid;
	}

	/**
	 * 根据Result填充字段
	 * @param rst 填充数据源Result
	 */
	public void fillByResult(Result rst)
	{
		this.setMid(Bytes.toString(rst.getRow()));
		this.setContent(Bytes.toString(rst.getValue(Bytes.toBytes("info"),
				Bytes.toBytes("content"))));
		this.setDateline(Long.parseLong(Bytes.toString(rst.getValue(Bytes.toBytes("info"),
				Bytes.toBytes("dateline")))));
		this.setIsread(Byte.parseByte(Bytes.toString(rst.getValue(Bytes.toBytes("info"),
				Bytes.toBytes("isread")))));
		this.setRecvuserId(Bytes.toString(rst.getValue(Bytes.toBytes("info"),
				Bytes.toBytes("recvuserid"))));
		this.setSenduserId(Bytes.toString(rst.getValue(Bytes.toBytes("info"),
				Bytes.toBytes("senduserid"))));
	}
}
