package org.chingo.gutcom.domain;

// Generated Apr 14, 2013 10:15:06 PM by Hibernate Tools 4.0.0

/**
 * CommonOplog generated by hbm2java
 */
public class CommonOplog implements java.io.Serializable
{

	private Long lid;
	private CommonUser commonUser;
	private String detail;
	private long dateline;

	public CommonOplog()
	{
	}

	public CommonOplog(CommonUser commonUser, String detail, long dateline)
	{
		this.commonUser = commonUser;
		this.detail = detail;
		this.dateline = dateline;
	}

	public Long getLid()
	{
		return this.lid;
	}

	public void setLid(Long lid)
	{
		this.lid = lid;
	}

	public CommonUser getCommonUser()
	{
		return this.commonUser;
	}

	public void setCommonUser(CommonUser commonUser)
	{
		this.commonUser = commonUser;
	}

	public String getDetail()
	{
		return this.detail;
	}

	public void setDetail(String detail)
	{
		this.detail = detail;
	}

	public long getDateline()
	{
		return this.dateline;
	}

	public void setDateline(long dateline)
	{
		this.dateline = dateline;
	}

}
