package org.chingo.gutcom.domain;

import org.apache.hadoop.hbase.client.Result;
import org.apache.hadoop.hbase.util.Bytes;

// Generated Apr 14, 2013 10:15:06 PM by Hibernate Tools 4.0.0

/**
 * CommonSysconf generated by hbm2java
 */
public class CommonSysconf implements java.io.Serializable
{

	private String confname; // rowKey，设置字段名
	private String confvalue; // 设置值

	public CommonSysconf()
	{
	}

	public CommonSysconf(String confname, String confvalue)
	{
		this.confname = confname;
		this.confvalue = confvalue;
	}

	public String getConfname()
	{
		return this.confname;
	}

	public void setConfname(String confname)
	{
		this.confname = confname;
	}

	public String getConfvalue()
	{
		return this.confvalue;
	}

	public void setConfvalue(String confvalue)
	{
		this.confvalue = confvalue;
	}

	/**
	 * 根据Result填充字段
	 * @param rst 填充数据源Result
	 */
	public void fillByResult(Result rst)
	{
		this.setConfname(Bytes.toString(rst.getRow()));
		this.setConfvalue(Bytes.toString(rst.getValue(Bytes.toBytes("info"),
				Bytes.toBytes("confvalue"))));
	}
}
