package org.chingo.gutcom.domain;

import org.apache.hadoop.hbase.client.Result;
import org.apache.hadoop.hbase.util.Bytes;

// Generated Apr 14, 2013 10:15:06 PM by Hibernate Tools 4.0.0

/**
 * CommonSyslog generated by hbm2java
 */
public class CommonSyslog implements java.io.Serializable
{

	private String lid; // rowKey，日志ID
	private String userid; // 操作用户ID
	private String nickname = ""; // 操作用户昵称
	private CommonUser user; // 用户对象
	private String detail; // 日志描述
	private long dateline; // 生成时间戳
	private String ip; // 用户IP
	private byte type; // 日志类型

	public CommonSyslog()
	{
	}

	public CommonSyslog(String lid, String userid, String nickname
			, String detail, long dateline, String ip, byte type)
	{
		this.lid = lid;
		this.userid = userid;
		this.nickname = nickname;
		this.detail = detail;
		this.dateline = dateline;
		this.ip = ip;
		this.type = type;
	}

	public String getLid()
	{
		return this.lid;
	}

	public void setLid(String lid)
	{
		this.lid = lid;
	}
	
	public String getUserid()
	{
		return this.userid;
	}
	
	public void setUserid(String userid)
	{
		this.userid = userid;
	}

	public String getNickname()
	{
		return nickname;
	}

	public void setNickname(String nickname)
	{
		this.nickname = nickname;
	}

	public CommonUser getUser()
	{
		return this.user;
	}

	public void setUser(CommonUser user)
	{
		this.user = user;
	}

	public String getDetail()
	{
		return this.detail;
	}

	public void setDetail(String detail)
	{
		this.detail = detail;
	}

	public long getDateline()
	{
		return this.dateline;
	}

	public void setDateline(long dateline)
	{
		this.dateline = dateline;
	}

	public String getIp()
	{
		return this.ip;
	}
	
	public void setIp(String ip)
	{
		this.ip = ip;
	}
	
	public byte getType()
	{
		return this.type;
	}
	
	public void setType(byte type)
	{
		this.type = type;
	}
	
	/**
	 * 根据Result填充字段
	 * @param rst 填充数据源Result
	 */
	public void fillByResult(Result rst)
	{
		this.setLid(Bytes.toString(rst.getRow()));
		this.setDetail(Bytes.toString(rst.getValue(Bytes.toBytes("info"), 
				Bytes.toBytes("detail"))));
		this.setUserid(Bytes.toString(rst.getValue(Bytes.toBytes("info"), 
				Bytes.toBytes("userid"))));
		// 存在用户昵称列时才填充，防止旧日志无该列而报错
		if(rst.containsColumn(Bytes.toBytes("info"), Bytes.toBytes("nickname")))
		{
			this.setNickname(Bytes.toString(rst.getValue(Bytes.toBytes("info"), 
					Bytes.toBytes("nickname"))));
		}
		this.setIp(Bytes.toString(rst.getValue(Bytes.toBytes("info"), 
				Bytes.toBytes("ip"))));
		this.setType(Byte.parseByte(Bytes.toString(rst.getValue(Bytes.toBytes("info"), 
				Bytes.toBytes("type")))));
		this.setDateline(Long.parseLong(Bytes.toString(rst.getValue(Bytes.toBytes("info"), 
				Bytes.toBytes("dateline")))));
	}
}
