package org.chingo.gutcom.domain;

// Generated Apr 14, 2013 10:15:06 PM by Hibernate Tools 4.0.0

/**
 * CommonSyslog generated by hbm2java
 */
public class CommonSyslog implements java.io.Serializable
{

	private String lid; // rowKey，日志ID
	private String userid; // 操作用户ID
	private CommonUser commonUser; // 用户对象
	private String detail; // 日志描述
	private long dateline; // 生成时间戳
	private String ip; // 用户IP
	private byte type; // 日志类型

	public CommonSyslog()
	{
	}

	public CommonSyslog(String lid, String userid, String detail,
			long dateline, String ip, byte type)
	{
		this.lid = lid;
		this.userid = userid;
		this.detail = detail;
		this.dateline = dateline;
		this.ip = ip;
		this.type = type;
	}

	public String getLid()
	{
		return this.lid;
	}

	public void setLid(String lid)
	{
		this.lid = lid;
	}
	
	public String getUserid()
	{
		return this.userid;
	}
	
	public void setUserid(String userid)
	{
		this.userid = userid;
	}

	public CommonUser getCommonUser()
	{
		return this.commonUser;
	}

	public void setCommonUser(CommonUser commonUser)
	{
		this.commonUser = commonUser;
	}

	public String getDetail()
	{
		return this.detail;
	}

	public void setDetail(String detail)
	{
		this.detail = detail;
	}

	public long getDateline()
	{
		return this.dateline;
	}

	public void setDateline(long dateline)
	{
		this.dateline = dateline;
	}

	public String getIp()
	{
		return this.ip;
	}
	
	public void setIp(String ip)
	{
		this.ip = ip;
	}
	
	public byte getType()
	{
		return this.type;
	}
	
	public void setType(byte type)
	{
		this.type = type;
	}
}
