package org.chingo.gutcom.domain;

// Generated Apr 14, 2013 10:15:06 PM by Hibernate Tools 4.0.0

/**
 * CommonSyslog generated by hbm2java
 */
public class CommonSyslog implements java.io.Serializable
{

	private Long lid;
	private CommonUser commonUser;
	private String detail;
	private long dateline;
	private String ip;
	private byte type;

	public CommonSyslog()
	{
	}

	public CommonSyslog(CommonUser commonUser, String detail,
			long dateline, String ip, byte type)
	{
		this.commonUser = commonUser;
		this.detail = detail;
		this.dateline = dateline;
		this.ip = ip;
		this.type = type;
	}

	public Long getLid()
	{
		return this.lid;
	}

	public void setLid(Long lid)
	{
		this.lid = lid;
	}

	public CommonUser getCommonUser()
	{
		return this.commonUser;
	}

	public void setCommonUser(CommonUser commonUser)
	{
		this.commonUser = commonUser;
	}

	public String getDetail()
	{
		return this.detail;
	}

	public void setDetail(String detail)
	{
		this.detail = detail;
	}

	public long getDateline()
	{
		return this.dateline;
	}

	public void setDateline(long dateline)
	{
		this.dateline = dateline;
	}

	public String getIp()
	{
		return this.ip;
	}
	
	public void setIp(String ip)
	{
		this.ip = ip;
	}
	
	public byte getType()
	{
		return this.type;
	}
	
	public void setType(byte type)
	{
		this.type = type;
	}
}
