package org.chingo.gutcom.domain;

// Generated Apr 14, 2013 10:15:06 PM by Hibernate Tools 4.0.0

/**
 * CommonMsgSend generated by hbm2java
 */
public class CommonMsgSend implements java.io.Serializable
{

	private Long mid;
	private CommonUser commonUserByRecvuser;
	private CommonUser commonUserBySenduser;
	private String content;
	private long dateline;

	public CommonMsgSend()
	{
	}

	public CommonMsgSend(CommonUser commonUserByRecvuser,
			CommonUser commonUserBySenduser, String content, long dateline)
	{
		this.commonUserByRecvuser = commonUserByRecvuser;
		this.commonUserBySenduser = commonUserBySenduser;
		this.content = content;
		this.dateline = dateline;
	}

	public Long getMid()
	{
		return this.mid;
	}

	public void setMid(Long mid)
	{
		this.mid = mid;
	}

	public CommonUser getCommonUserByRecvuser()
	{
		return this.commonUserByRecvuser;
	}

	public void setCommonUserByRecvuser(CommonUser commonUserByRecvuser)
	{
		this.commonUserByRecvuser = commonUserByRecvuser;
	}

	public CommonUser getCommonUserBySenduser()
	{
		return this.commonUserBySenduser;
	}

	public void setCommonUserBySenduser(CommonUser commonUserBySenduser)
	{
		this.commonUserBySenduser = commonUserBySenduser;
	}

	public String getContent()
	{
		return this.content;
	}

	public void setContent(String content)
	{
		this.content = content;
	}

	public long getDateline()
	{
		return this.dateline;
	}

	public void setDateline(long dateline)
	{
		this.dateline = dateline;
	}

}
