package org.chingo.gutcom.domain;

// Generated Apr 14, 2013 10:15:06 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * CommonUser generated by hbm2java
 */
public class CommonUser implements java.io.Serializable
{

	private String uid;
	private String nickname;
	private String email;
	private String studentnum;
	private String password;
	private byte status;
	private long regdate;
	private String regip;
	private String realname;
	private String college;
	private String major;
	private String classname;
	private byte gender;
	private int birthyear;
	private byte birthmonth;
	private byte birthday;
	private String constellation;
	private String zodiac;
	private String bloodtype;
	private String qq;
	private String selfintro;
	private String avatarurl;
	private String bigavatarurl;
	
	private long lastlogin;
	private String lastip;
	private int weibocnt;
	private int follower;
	private int following;
	private int newfollower;
	private int newmsg;
	private int newat;
	private int newcomment;

	public CommonUser()
	{
	}

	public CommonUser(String nickname, String email, String studentnum,
			String password, byte status, long regdate)
	{
		this.nickname = nickname;
		this.email = email;
		this.studentnum = studentnum;
		this.password = password;
		this.status = status;
		this.regdate = regdate;
	}

	public CommonUser(String nickname, String email, String studentnum,
			String password, byte status, long regdate,
			String regip, String realname, String college,
			String major, String classname, byte gender,
			int birthyear, byte birthmonth, byte birthday,
			String constellation, String zodiac, String bloodtype,
			String qq, String selfintro, String avatarurl,
			String bigavatarurl)
	{
		this.nickname = nickname;
		this.email = email;
		this.studentnum = studentnum;
		this.password = password;
		this.status = status;
		this.regdate = regdate;
		this.regip = regip;
		this.realname = realname;
		this.college = college;
		this.major = major;
		this.classname = classname;
		this.gender = gender;
		this.birthyear = birthyear;
		this.birthmonth = birthmonth;
		this.birthday = birthday;
		this.constellation = constellation;
		this.zodiac = zodiac;
		this.bloodtype = bloodtype;
		this.qq = qq;
		this.selfintro = selfintro;
		this.avatarurl = avatarurl;
		this.bigavatarurl = bigavatarurl;
	}

	public String getUid()
	{
		return this.uid;
	}

	public void setUid(String uid)
	{
		this.uid = uid;
	}

	public String getNickname()
	{
		return this.nickname;
	}

	public void setNickname(String nickname)
	{
		this.nickname = nickname;
	}

	public String getEmail()
	{
		return this.email;
	}

	public void setEmail(String email)
	{
		this.email = email;
	}

	public String getStudentnum()
	{
		return this.studentnum;
	}

	public void setStudentnum(String studentnum)
	{
		this.studentnum = studentnum;
	}

	public String getPassword()
	{
		return this.password;
	}

	public void setPassword(String password)
	{
		this.password = password;
	}

	public byte getStatus()
	{
		return this.status;
	}

	public void setStatus(byte status)
	{
		this.status = status;
	}

	public long getRegdate()
	{
		return this.regdate;
	}

	public void setRegdate(long regdate)
	{
		this.regdate = regdate;
	}

}
