package org.chingo.gutcom.domain;

// Generated Apr 14, 2013 10:15:06 PM by Hibernate Tools 4.0.0

/**
 * CommonSmile generated by hbm2java
 */
public class CommonSmile implements java.io.Serializable
{

	private String sid; // rowKey，表情ID
	private String description; // 表情描述
	private String imgurl; // 表情图片地址
	private int order; // 表情顺序

	public CommonSmile()
	{
	}

	public CommonSmile(String sid, String description,
			String imgurl, int order)
	{
		this.sid = sid;
		this.description = description;
		this.imgurl = imgurl;
		this.order = order;
	}

	public String getSid()
	{
		return this.sid;
	}

	public void setSid(String sid)
	{
		this.sid = sid;
	}

	public String getDescription()
	{
		return this.description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}

	public String getImgurl()
	{
		return this.imgurl;
	}

	public void setImgurl(String imgurl)
	{
		this.imgurl = imgurl;
	}

	public int getOrder()
	{
		return this.order;
	}

	public void setOrder(int order)
	{
		this.order = order;
	}

}
