package org.chingo.gutcom.domain;

// Generated Apr 14, 2013 10:15:06 PM by Hibernate Tools 4.0.0

/**
 * CommonUser generated by hbm2java
 */
public class CommonUser implements java.io.Serializable
{
	/* Family : info */
	private String uid; // rowKey，用户ID
	private String nickname; // 用户昵称，唯一
	private String email; // 邮箱地址，唯一
	private String studentnum = ""; // 绑定学号，唯一
	private String password; // 密码，MD5加密
	private byte status = 0; // 用户状态
	private long regdate; // 注册时间戳
	private String regip; // 注册IP
	private String realname = ""; // 真实姓名
	private String college = ""; // 所在学院
	private String major = ""; // 就读专业
	private String classname = ""; // 班级名称
	private byte gender = 0; // 性别
	private int birthyear = 0; // 出生年
	private byte birthmonth = 0; // 出生月
	private byte birthday = 0; // 出生日
	private String constellation = ""; // 星座
	private String zodiac = ""; // 生肖
	private String bloodtype = ""; // 血型
	private String qq = ""; // QQ号码
	private String selfintro = ""; // 自我简介
	private String avatarurl = ""; // 标准头像地址
	private String bigavatarurl = ""; // 大头像地址
	/* Family : profile */
	private long lastlogin = 0L; // 上次登录时间戳
	private String lastip = ""; // 上次登录IP
	private int weibocnt = 0; // 已发微博总数
	private int follower = 0; // 粉丝总数
	private int following = 0; // 关注总数
	private int newfollower = 0; // 新粉丝数
	private int newmsg = 0; // 新消息数
	private int newat = 0; // 新@提到数
	private int newcomment = 0; // 新评论数

	public CommonUser()
	{
	}

	public CommonUser(String nickname, String email, String studentnum,
			String password, byte status, long regdate)
	{
		this.nickname = nickname;
		this.email = email;
		this.studentnum = studentnum;
		this.password = password;
		this.status = status;
		this.regdate = regdate;
	}

	public CommonUser(String nickname, String email, String studentnum,
			String password, byte status, long regdate,
			String regip, String realname, String college,
			String major, String classname, byte gender,
			int birthyear, byte birthmonth, byte birthday,
			String constellation, String zodiac, String bloodtype,
			String qq, String selfintro, String avatarurl,
			String bigavatarurl)
	{
		this.nickname = nickname;
		this.email = email;
		this.studentnum = studentnum;
		this.password = password;
		this.status = status;
		this.regdate = regdate;
		this.regip = regip;
		this.realname = realname;
		this.college = college;
		this.major = major;
		this.classname = classname;
		this.gender = gender;
		this.birthyear = birthyear;
		this.birthmonth = birthmonth;
		this.birthday = birthday;
		this.constellation = constellation;
		this.zodiac = zodiac;
		this.bloodtype = bloodtype;
		this.qq = qq;
		this.selfintro = selfintro;
		this.avatarurl = avatarurl;
		this.bigavatarurl = bigavatarurl;
	}

	public String getUid()
	{
		return this.uid;
	}

	public void setUid(String uid)
	{
		this.uid = uid;
	}

	public String getNickname()
	{
		return this.nickname;
	}

	public void setNickname(String nickname)
	{
		this.nickname = nickname;
	}

	public String getEmail()
	{
		return this.email;
	}

	public void setEmail(String email)
	{
		this.email = email;
	}

	public String getStudentnum()
	{
		return this.studentnum;
	}

	public void setStudentnum(String studentnum)
	{
		this.studentnum = studentnum;
	}

	public String getPassword()
	{
		return this.password;
	}

	public void setPassword(String password)
	{
		this.password = password;
	}

	public byte getStatus()
	{
		return this.status;
	}

	public void setStatus(byte status)
	{
		this.status = status;
	}

	public long getRegdate()
	{
		return this.regdate;
	}

	public void setRegdate(long regdate)
	{
		this.regdate = regdate;
	}

	public String getRegip()
	{
		return regip;
	}

	public void setRegip(String regip)
	{
		this.regip = regip;
	}

	public String getRealname()
	{
		return realname;
	}

	public void setRealname(String realname)
	{
		this.realname = realname;
	}

	public String getCollege()
	{
		return college;
	}

	public void setCollege(String college)
	{
		this.college = college;
	}

	public String getMajor()
	{
		return major;
	}

	public void setMajor(String major)
	{
		this.major = major;
	}

	public String getClassname()
	{
		return classname;
	}

	public void setClassname(String classname)
	{
		this.classname = classname;
	}

	public byte getGender()
	{
		return gender;
	}

	public void setGender(byte gender)
	{
		this.gender = gender;
	}

	public int getBirthyear()
	{
		return birthyear;
	}

	public void setBirthyear(int birthyear)
	{
		this.birthyear = birthyear;
	}

	public byte getBirthmonth()
	{
		return birthmonth;
	}

	public void setBirthmonth(byte birthmonth)
	{
		this.birthmonth = birthmonth;
	}

	public byte getBirthday()
	{
		return birthday;
	}

	public void setBirthday(byte birthday)
	{
		this.birthday = birthday;
	}

	public String getConstellation()
	{
		return constellation;
	}

	public void setConstellation(String constellation)
	{
		this.constellation = constellation;
	}

	public String getZodiac()
	{
		return zodiac;
	}

	public void setZodiac(String zodiac)
	{
		this.zodiac = zodiac;
	}

	public String getBloodtype()
	{
		return bloodtype;
	}

	public void setBloodtype(String bloodtype)
	{
		this.bloodtype = bloodtype;
	}

	public String getQq()
	{
		return qq;
	}

	public void setQq(String qq)
	{
		this.qq = qq;
	}

	public String getSelfintro()
	{
		return selfintro;
	}

	public void setSelfintro(String selfintro)
	{
		this.selfintro = selfintro;
	}

	public String getAvatarurl()
	{
		return avatarurl;
	}

	public void setAvatarurl(String avatarurl)
	{
		this.avatarurl = avatarurl;
	}

	public String getBigavatarurl()
	{
		return bigavatarurl;
	}

	public void setBigavatarurl(String bigavatarurl)
	{
		this.bigavatarurl = bigavatarurl;
	}

	public long getLastlogin()
	{
		return lastlogin;
	}

	public void setLastlogin(long lastlogin)
	{
		this.lastlogin = lastlogin;
	}

	public String getLastip()
	{
		return lastip;
	}

	public void setLastip(String lastip)
	{
		this.lastip = lastip;
	}

	public int getWeibocnt()
	{
		return weibocnt;
	}

	public void setWeibocnt(int weibocnt)
	{
		this.weibocnt = weibocnt;
	}

	public int getFollower()
	{
		return follower;
	}

	public void setFollower(int follower)
	{
		this.follower = follower;
	}

	public int getFollowing()
	{
		return following;
	}

	public void setFollowing(int following)
	{
		this.following = following;
	}

	public int getNewfollower()
	{
		return newfollower;
	}

	public void setNewfollower(int newfollower)
	{
		this.newfollower = newfollower;
	}

	public int getNewmsg()
	{
		return newmsg;
	}

	public void setNewmsg(int newmsg)
	{
		this.newmsg = newmsg;
	}

	public int getNewat()
	{
		return newat;
	}

	public void setNewat(int newat)
	{
		this.newat = newat;
	}

	public int getNewcomment()
	{
		return newcomment;
	}

	public void setNewcomment(int newcomment)
	{
		this.newcomment = newcomment;
	}

}
