package org.chingo.gutcom.domain;

// Generated Apr 14, 2013 10:15:06 PM by Hibernate Tools 4.0.0

/**
 * ShareStatus generated by hbm2java
 */
public class ShareStatus implements java.io.Serializable
{

	private long sid;
	private ShareContent shareContent;
	private int viewcnt;

	public ShareStatus()
	{
	}

	public ShareStatus(ShareContent shareContent, int viewcnt)
	{
		this.shareContent = shareContent;
		this.viewcnt = viewcnt;
	}

	public long getSid()
	{
		return this.sid;
	}

	public void setSid(long sid)
	{
		this.sid = sid;
	}

	public ShareContent getShareContent()
	{
		return this.shareContent;
	}

	public void setShareContent(ShareContent shareContent)
	{
		this.shareContent = shareContent;
	}

	public int getViewcnt()
	{
		return this.viewcnt;
	}

	public void setViewcnt(int viewcnt)
	{
		this.viewcnt = viewcnt;
	}

}
