package org.chingo.gutcom.domain;

// Generated Apr 14, 2013 10:15:06 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * ShareCategory generated by hbm2java
 */
public class ShareCategory implements java.io.Serializable
{

	private Integer cid;
	private String catename;
	private Set<ShareContent> shareContents = new HashSet<ShareContent>(0);

	public ShareCategory()
	{
	}

	public ShareCategory(String catename)
	{
		this.catename = catename;
	}

	public ShareCategory(String catename, Set<ShareContent> shareContents)
	{
		this.catename = catename;
		this.shareContents = shareContents;
	}

	public Integer getCid()
	{
		return this.cid;
	}

	public void setCid(Integer cid)
	{
		this.cid = cid;
	}

	public String getCatename()
	{
		return this.catename;
	}

	public void setCatename(String catename)
	{
		this.catename = catename;
	}

	public Set<ShareContent> getShareContents()
	{
		return this.shareContents;
	}

	public void setShareContents(Set<ShareContent> shareContents)
	{
		this.shareContents = shareContents;
	}

}
