package org.chingo.gutcom.domain;

// Generated Apr 14, 2013 10:15:06 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * WeiboTopic generated by hbm2java
 */
public class WeiboTopic implements java.io.Serializable
{

	private Long tid;
	private CommonUser commonUser;
	private WeiboContent weiboContent;
	private String title;
	private int count;
	private long dateline;
	private byte isblock;
	private Set<WeiboTopicRelation> weiboTopicRelations = new HashSet<WeiboTopicRelation>(
			0);
	private Set<WeiboTopicFollow> weiboTopicFollows = new HashSet<WeiboTopicFollow>(
			0);

	public WeiboTopic()
	{
	}

	public WeiboTopic(CommonUser commonUser, WeiboContent weiboContent,
			String title, int count, long dateline, byte isblock)
	{
		this.commonUser = commonUser;
		this.weiboContent = weiboContent;
		this.title = title;
		this.count = count;
		this.dateline = dateline;
		this.isblock = isblock;
	}

	public WeiboTopic(CommonUser commonUser, WeiboContent weiboContent,
			String title, int count, long dateline, byte isblock,
			Set<WeiboTopicRelation> weiboTopicRelations,
			Set<WeiboTopicFollow> weiboTopicFollows)
	{
		this.commonUser = commonUser;
		this.weiboContent = weiboContent;
		this.title = title;
		this.count = count;
		this.dateline = dateline;
		this.isblock = isblock;
		this.weiboTopicRelations = weiboTopicRelations;
		this.weiboTopicFollows = weiboTopicFollows;
	}

	public Long getTid()
	{
		return this.tid;
	}

	public void setTid(Long tid)
	{
		this.tid = tid;
	}

	public CommonUser getCommonUser()
	{
		return this.commonUser;
	}

	public void setCommonUser(CommonUser commonUser)
	{
		this.commonUser = commonUser;
	}

	public WeiboContent getWeiboContent()
	{
		return this.weiboContent;
	}

	public void setWeiboContent(WeiboContent weiboContent)
	{
		this.weiboContent = weiboContent;
	}

	public String getTitle()
	{
		return this.title;
	}

	public void setTitle(String title)
	{
		this.title = title;
	}

	public int getCount()
	{
		return this.count;
	}

	public void setCount(int count)
	{
		this.count = count;
	}

	public long getDateline()
	{
		return this.dateline;
	}

	public void setDateline(long dateline)
	{
		this.dateline = dateline;
	}

	public byte getIsblock()
	{
		return this.isblock;
	}

	public void setIsblock(byte isblock)
	{
		this.isblock = isblock;
	}

	public Set<WeiboTopicRelation> getWeiboTopicRelations()
	{
		return this.weiboTopicRelations;
	}

	public void setWeiboTopicRelations(
			Set<WeiboTopicRelation> weiboTopicRelations)
	{
		this.weiboTopicRelations = weiboTopicRelations;
	}

	public Set<WeiboTopicFollow> getWeiboTopicFollows()
	{
		return this.weiboTopicFollows;
	}

	public void setWeiboTopicFollows(Set<WeiboTopicFollow> weiboTopicFollows)
	{
		this.weiboTopicFollows = weiboTopicFollows;
	}

}
