package org.chingo.gutcom.domain;

// Generated Apr 14, 2013 10:15:06 PM by Hibernate Tools 4.0.0


/**
 * WeiboFollowGroup generated by hbm2java
 */
public class WeiboFollowGroup implements java.io.Serializable
{
	private String groupName; // rowKey，分组名

	public WeiboFollowGroup()
	{
	}

	public WeiboFollowGroup(String groupname)
	{
		this.groupName = groupname;
	}

	public String getGroupName()
	{
		return this.groupName;
	}

	public void setGroupName(String groupName)
	{
		this.groupName = groupName;
	}
}
