package org.chingo.gutcom.domain;

// Generated Apr 14, 2013 10:15:06 PM by Hibernate Tools 4.0.0

/**
 * WeiboTopicFollow generated by hbm2java
 */
public class WeiboTopicFollow implements java.io.Serializable
{

	private String id; // rowKey，关注ID
	private String topicTitle; // 关注话题的标题
	private String userId; // 关注的用户ID

	public WeiboTopicFollow()
	{
	}

	public WeiboTopicFollow(String id, String topicTitle, String userId)
	{
		this.id = id;
		this.topicTitle = topicTitle;
		this.userId = userId;
	}

	public String getId()
	{
		return this.id;
	}

	public void setId(String id)
	{
		this.id = id;
	}
	
	public String getTopicTitle()
	{
		return topicTitle;
	}

	public void setTopicTitle(String topicTitle)
	{
		this.topicTitle = topicTitle;
	}

	public String getUserId()
	{
		return userId;
	}

	public void setUserId(String userId)
	{
		this.userId = userId;
	}

}
