package org.chingo.gutcom.domain;

// Generated Apr 14, 2013 10:15:06 PM by Hibernate Tools 4.0.0

/**
 * WeiboTopic generated by hbm2java
 */
public class WeiboTopic implements java.io.Serializable
{
	private String title;
	private int count;
	private long dateline;
	private byte isblock;
	private String sponsorId;
	private CommonUser sponsor;
	private long lastpost;

	public WeiboTopic()
	{
	}

	public WeiboTopic(String title, int count, long dateline,
			byte isblock, String sponsorId, long lastpost)
	{
		this.title = title;
		this.count = count;
		this.dateline = dateline;
		this.isblock = isblock;
		this.sponsorId = sponsorId;
		this.lastpost = lastpost;
	}

	public String getTitle()
	{
		return this.title;
	}

	public void setTitle(String title)
	{
		this.title = title;
	}

	public int getCount()
	{
		return this.count;
	}

	public void setCount(int count)
	{
		this.count = count;
	}

	public long getDateline()
	{
		return this.dateline;
	}

	public void setDateline(long dateline)
	{
		this.dateline = dateline;
	}

	public byte getIsblock()
	{
		return this.isblock;
	}

	public void setIsblock(byte isblock)
	{
		this.isblock = isblock;
	}

	public String getSponsorId()
	{
		return sponsorId;
	}

	public void setSponsorId(String sponsorId)
	{
		this.sponsorId = sponsorId;
	}

	public CommonUser getSponsor()
	{
		return sponsor;
	}

	public void setSponsor(CommonUser sponsor)
	{
		this.sponsor = sponsor;
	}

	public long getLastpost()
	{
		return lastpost;
	}

	public void setLastpost(long lastpost)
	{
		this.lastpost = lastpost;
	}

}
