package org.chingo.gutcom.domain;

// Generated Apr 14, 2013 10:15:06 PM by Hibernate Tools 4.0.0

/**
 * WeiboFav generated by hbm2java
 */
public class WeiboFav implements java.io.Serializable
{

	private String fid; // rowKey，收藏ID
	private String userId; // 收藏用户的ID
	private String weiboId; // 被收藏微博的ID

	public WeiboFav()
	{
	}

	public WeiboFav(String fid, String userId, String weiboId)
	{
		this.fid = fid;
		this.userId = userId;
		this.weiboId = weiboId;
	}

	public String getFid()
	{
		return this.fid;
	}

	public void setFid(String fid)
	{
		this.fid = fid;
	}

	public String getUserId()
	{
		return userId;
	}

	public void setUserId(String userId)
	{
		this.userId = userId;
	}

	public String getWeiboId()
	{
		return weiboId;
	}

	public void setWeiboId(String weiboId)
	{
		this.weiboId = weiboId;
	}

}
