package org.chingo.gutcom.domain;

// Generated Apr 14, 2013 10:15:06 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import org.apache.hadoop.hbase.client.Result;
import org.apache.hadoop.hbase.util.Bytes;

/**
 * WeiboContent generated by hbm2java
 */
public class WeiboContent implements java.io.Serializable
{

	private String wid; // rowKey，微博ID
	private String authorid; // 作者ID
	private CommonUser author; // 作者用户对象
	private String content; // 微博内容
	private String sourceid = "0"; // 源微博ID，转发或评论时可用
	private WeiboContent source; // 源微博对象
	private String sourceContent = ""; // 源微博内容
	private byte type = 0; // 微博类型
	private byte format = 0; // 微博内容格式
	private byte visibility = 0; // 微博可见性
	private byte status = 0; // 微博状态
	private String thumbnailPic = ""; // 缩略图地址
	private String middlePic = ""; // 标准图地址
	private String originalPic = ""; // 原始图地址
	private long dateline; // 发表时间戳
	private String topicTitles = ""; // 所属话题标题，多个用#隔开
	private Set<WeiboTopic> topics = new HashSet<WeiboTopic>(0); // 所属话题集合对象

	public WeiboContent()
	{
	}

	public WeiboContent(String wid, String authorid, String content, String sourceid,
			byte type, byte format, byte visibility, byte status,
			String thumbnailPic, String middlePic, String originalPic,
			long dateline, String topicTitles)
	{
		this.wid = wid;
		this.authorid = authorid;
		this.content = content;
		this.sourceid = sourceid;
		this.type = type;
		this.format = format;
		this.visibility = visibility;
		this.status = status;
		this.thumbnailPic = thumbnailPic;
		this.middlePic = middlePic;
		this.originalPic = originalPic;
		this.dateline = dateline;
		this.topicTitles = topicTitles;
	}

	public Set<WeiboTopic> getTopics()
	{
		return topics;
	}

	public void setTopics(Set<WeiboTopic> topics)
	{
		this.topics = topics;
	}

	public String getTopicTitles()
	{
		return topicTitles;
	}

	public void setTopicTitles(String topicTitles)
	{
		this.topicTitles = topicTitles;
	}

	public String getWid()
	{
		return this.wid;
	}

	public void setWid(String wid)
	{
		this.wid = wid;
	}

	public String getContent()
	{
		return this.content;
	}

	public void setContent(String content)
	{
		this.content = content;
	}

	public String getSourceid()
	{
		return this.sourceid;
	}

	public void setSourceid(String sourceid)
	{
		this.sourceid = sourceid;
	}

	public byte getType()
	{
		return this.type;
	}

	public void setType(byte type)
	{
		this.type = type;
	}

	public byte getFormat()
	{
		return this.format;
	}

	public void setFormat(byte format)
	{
		this.format = format;
	}

	public byte getVisibility()
	{
		return this.visibility;
	}

	public void setVisibility(byte visibility)
	{
		this.visibility = visibility;
	}

	public byte getStatus()
	{
		return this.status;
	}

	public void setStatus(byte status)
	{
		this.status = status;
	}

	public String getThumbnailPic()
	{
		return this.thumbnailPic;
	}

	public void setThumbnailPic(String thumbnailPic)
	{
		this.thumbnailPic = thumbnailPic;
	}

	public String getMiddlePic()
	{
		return this.middlePic;
	}

	public void setMiddlePic(String middlePic)
	{
		this.middlePic = middlePic;
	}

	public String getOriginalPic()
	{
		return this.originalPic;
	}

	public void setOriginalPic(String originalPic)
	{
		this.originalPic = originalPic;
	}

	public long getDateline()
	{
		return this.dateline;
	}

	public void setDateline(long dateline)
	{
		this.dateline = dateline;
	}

	public String getAuthorid()
	{
		return authorid;
	}

	public void setAuthorid(String authorid)
	{
		this.authorid = authorid;
	}

	public WeiboContent getSource()
	{
		return source;
	}

	public void setSource(WeiboContent source)
	{
		this.source = source;
	}

	public String getSourceContent()
	{
		return sourceContent;
	}

	public void setSourceContent(String sourceContent)
	{
		this.sourceContent = sourceContent;
	}
	
	public CommonUser getAuthor()
	{
		return this.author;
	}
	
	public void setAuthor(CommonUser author)
	{
		this.author = author;
	}

	/**
	 * 根据Result填充字段
	 * @param rst 填充数据源Result
	 */
	public void fillByResult(Result rst)
	{
		this.setWid(Bytes.toString(rst.getRow()));
		this.setAuthorid(Bytes.toString(rst.getValue(Bytes.toBytes("info"),
				Bytes.toBytes("authorid"))));
		this.setContent(Bytes.toString(rst.getValue(Bytes.toBytes("info"),
				Bytes.toBytes("content"))));
		this.setSourceid(Bytes.toString(rst.getValue(Bytes.toBytes("info"),
				Bytes.toBytes("sourceid"))));
		this.setSourceContent(Bytes.toString(rst.getValue(Bytes.toBytes("info"),
				Bytes.toBytes("source_content"))));
		this.setType(Byte.parseByte(Bytes.toString(rst.getValue(Bytes.toBytes("info"),
				Bytes.toBytes("type")))));
		this.setFormat(Byte.parseByte(Bytes.toString(rst.getValue(Bytes.toBytes("info"),
				Bytes.toBytes("format")))));
		this.setVisibility(Byte.parseByte(Bytes.toString(rst.getValue(Bytes.toBytes("info"),
				Bytes.toBytes("visibility")))));
		this.setStatus(Byte.parseByte(Bytes.toString(rst.getValue(Bytes.toBytes("info"),
				Bytes.toBytes("status")))));
		this.setThumbnailPic(Bytes.toString(rst.getValue(Bytes.toBytes("info"),
				Bytes.toBytes("thumbnail_pic"))));
		this.setMiddlePic(Bytes.toString(rst.getValue(Bytes.toBytes("info"),
				Bytes.toBytes("middle_pic"))));
		this.setOriginalPic(Bytes.toString(rst.getValue(Bytes.toBytes("info"),
				Bytes.toBytes("original_pic"))));
		this.setDateline(Long.parseLong(Bytes.toString(rst.getValue(Bytes.toBytes("info"),
				Bytes.toBytes("dateline")))));
		this.setTopicTitles(Bytes.toString(rst.getValue(Bytes.toBytes("info"),
				Bytes.toBytes("topic_titles"))));
	}
}
