package org.chingo.gutcom.domain;

// Generated Apr 14, 2013 10:15:06 PM by Hibernate Tools 4.0.0

/**
 * WeiboTopicRelation generated by hbm2java
 */
public class WeiboTopicRelation implements java.io.Serializable
{

	private String id; // rowKey，关系ID
	private String topicTitle; // 话题标题
	private String weiboId; // 微博ID

	public WeiboTopicRelation()
	{
	}

	public WeiboTopicRelation(String id, String topicTitle, String weiboId)
	{
		this.id = id;
		this.topicTitle = topicTitle;
		this.weiboId = weiboId;
	}

	public String getId()
	{
		return this.id;
	}

	public void setId(String id)
	{
		this.id = id;
	}

	public String getTopicTitle()
	{
		return topicTitle;
	}

	public void setTopicTitle(String topicTitle)
	{
		this.topicTitle = topicTitle;
	}

	public String getWeiboId()
	{
		return weiboId;
	}

	public void setWeiboId(String weiboId)
	{
		this.weiboId = weiboId;
	}

}
