package org.chingo.gutcom.domain;

import org.apache.hadoop.hbase.client.Result;
import org.apache.hadoop.hbase.util.Bytes;

// Generated Apr 14, 2013 10:15:06 PM by Hibernate Tools 4.0.0

/**
 * WeiboTopic generated by hbm2java
 */
public class WeiboTopic implements java.io.Serializable
{
	private String title; // 标题，rowKey
	private int count; // 下属微博总数
	private long dateline; // 发起时间戳
	private byte isblock; // 屏蔽标记，0-未屏蔽，1-已屏蔽
	private String sponsorId; // 发起者ID
	private CommonUser sponsor; // 发起者用户对象
	private long lastpost; // 最后发表微博的时间戳

	public WeiboTopic()
	{
	}

	public WeiboTopic(String title, int count, long dateline,
			byte isblock, String sponsorId, long lastpost)
	{
		this.title = title;
		this.count = count;
		this.dateline = dateline;
		this.isblock = isblock;
		this.sponsorId = sponsorId;
		this.lastpost = lastpost;
	}

	public String getTitle()
	{
		return this.title;
	}

	public void setTitle(String title)
	{
		this.title = title;
	}

	public int getCount()
	{
		return this.count;
	}

	public void setCount(int count)
	{
		this.count = count;
	}

	public long getDateline()
	{
		return this.dateline;
	}

	public void setDateline(long dateline)
	{
		this.dateline = dateline;
	}

	public byte getIsblock()
	{
		return this.isblock;
	}

	public void setIsblock(byte isblock)
	{
		this.isblock = isblock;
	}

	public String getSponsorId()
	{
		return sponsorId;
	}

	public void setSponsorId(String sponsorId)
	{
		this.sponsorId = sponsorId;
	}

	public CommonUser getSponsor()
	{
		return sponsor;
	}

	public void setSponsor(CommonUser sponsor)
	{
		this.sponsor = sponsor;
	}

	public long getLastpost()
	{
		return lastpost;
	}

	public void setLastpost(long lastpost)
	{
		this.lastpost = lastpost;
	}

	/**
	 * 根据Result填充字段
	 * @param rst 填充数据源Result
	 */
	public void fillByResult(Result rst)
	{
		this.setTitle(Bytes.toString(rst.getRow()));
		this.setSponsorId(Bytes.toString(rst.getValue(Bytes.toBytes("info"),
				Bytes.toBytes("sponsorid"))));
		this.setCount(Integer.parseInt(Bytes.toString(rst.getValue(Bytes.toBytes("info"),
				Bytes.toBytes("count")))));
		this.setDateline(Long.parseLong(Bytes.toString(rst.getValue(Bytes.toBytes("info"),
				Bytes.toBytes("dateline")))));
		this.setIsblock(Byte.parseByte(Bytes.toString(rst.getValue(Bytes.toBytes("info"),
				Bytes.toBytes("isblock")))));
		this.setLastpost(Long.parseLong(Bytes.toString(rst.getValue(Bytes.toBytes("info"),
				Bytes.toBytes("lastpost")))));
	}
}
