package org.chingo.gutcom.domain;

// Generated Apr 14, 2013 10:15:06 PM by Hibernate Tools 4.0.0

/**
 * WeiboFollow generated by hbm2java
 */
public class WeiboFollow implements java.io.Serializable
{

	private Long id;
	private WeiboFollowGroup weiboFollowGroup;
	private CommonUser commonUserByFollowuid;
	private CommonUser commonUserByUid;
	private String remark;

	public WeiboFollow()
	{
	}

	public WeiboFollow(WeiboFollowGroup weiboFollowGroup,
			CommonUser commonUserByFollowuid, CommonUser commonUserByUid,
			String remark)
	{
		this.weiboFollowGroup = weiboFollowGroup;
		this.commonUserByFollowuid = commonUserByFollowuid;
		this.commonUserByUid = commonUserByUid;
		this.remark = remark;
	}

	public Long getId()
	{
		return this.id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	public WeiboFollowGroup getWeiboFollowGroup()
	{
		return this.weiboFollowGroup;
	}

	public void setWeiboFollowGroup(WeiboFollowGroup weiboFollowGroup)
	{
		this.weiboFollowGroup = weiboFollowGroup;
	}

	public CommonUser getCommonUserByFollowuid()
	{
		return this.commonUserByFollowuid;
	}

	public void setCommonUserByFollowuid(CommonUser commonUserByFollowuid)
	{
		this.commonUserByFollowuid = commonUserByFollowuid;
	}

	public CommonUser getCommonUserByUid()
	{
		return this.commonUserByUid;
	}

	public void setCommonUserByUid(CommonUser commonUserByUid)
	{
		this.commonUserByUid = commonUserByUid;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

}
