package org.chingo.gutcom.domain;

import org.apache.hadoop.hbase.client.Result;
import org.apache.hadoop.hbase.util.Bytes;

// Generated Apr 14, 2013 10:15:06 PM by Hibernate Tools 4.0.0

/**
 * WeiboFav generated by hbm2java
 */
public class WeiboFav implements java.io.Serializable
{

	private String fid; // rowKey，收藏ID
	private String userId; // 收藏用户的ID
	private String weiboId; // 被收藏微博的ID

	public WeiboFav()
	{
	}

	public WeiboFav(String fid, String userId, String weiboId)
	{
		this.fid = fid;
		this.userId = userId;
		this.weiboId = weiboId;
	}

	public String getFid()
	{
		return this.fid;
	}

	public void setFid(String fid)
	{
		this.fid = fid;
	}

	public String getUserId()
	{
		return userId;
	}

	public void setUserId(String userId)
	{
		this.userId = userId;
	}

	public String getWeiboId()
	{
		return weiboId;
	}

	public void setWeiboId(String weiboId)
	{
		this.weiboId = weiboId;
	}

	/**
	 * 根据Result填充字段
	 * @param rst 填充数据源Result
	 */
	public void fillByResult(Result rst)
	{
		this.setFid(Bytes.toString(rst.getRow()));
		this.setUserId(Bytes.toString(rst.getValue(Bytes.toBytes("info"), 
				Bytes.toBytes("userid"))));
		this.setWeiboId(Bytes.toString(rst.getValue(Bytes.toBytes("info"), 
				Bytes.toBytes("weiboid"))));
	}
}
