package org.chingo.gutcom.domain;

// Generated Apr 14, 2013 10:15:06 PM by Hibernate Tools 4.0.0

/**
 * WeiboAt generated by hbm2java
 */
public class WeiboAt implements java.io.Serializable
{

	private String id; // rowKey，提到ID
	private String userId; // 提到的用户的ID
	private String weiboId; // 提到的微博的ID

	public WeiboAt()
	{
	}

	public WeiboAt(String id, String userId, String weiboId)
	{
		this.id = id;
		this.userId = userId;
		this.weiboId = weiboId;
	}

	public String getId()
	{
		return this.id;
	}

	public void setId(String id)
	{
		this.id = id;
	}

	public String getUserId()
	{
		return userId;
	}

	public void setUserId(String userId)
	{
		this.userId = userId;
	}

	public String getWeiboId()
	{
		return weiboId;
	}

	public void setWeiboId(String weiboId)
	{
		this.weiboId = weiboId;
	}

}
