package org.chingo.gutcom.domain;

import org.apache.hadoop.hbase.client.Result;
import org.apache.hadoop.hbase.util.Bytes;

// Generated Apr 14, 2013 10:15:06 PM by Hibernate Tools 4.0.0

/**
 * WeiboFollow generated by hbm2java
 */
public class WeiboFollow implements java.io.Serializable
{

	private String id; // rowKey， 关注ID
	private String userId; // 关注用户的ID
	private String followId; // 被关注用户的ID
	private String groupName = ""; // 关注分组名
	private String remark = ""; // 被关注用户的备注名

	public WeiboFollow()
	{
	}

	public WeiboFollow(String id, String userId, String followId,
			String groupName, String remark)
	{
		this.id = id;
		this.userId = userId;
		this.followId = followId;
		this.groupName = groupName;
		this.remark = remark;
	}

	public String getId()
	{
		return this.id;
	}

	public void setId(String id)
	{
		this.id = id;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public String getUserId()
	{
		return userId;
	}

	public void setUserId(String userId)
	{
		this.userId = userId;
	}

	public String getFollowId()
	{
		return followId;
	}

	public void setFollowId(String followId)
	{
		this.followId = followId;
	}

	public String getGroupName()
	{
		return groupName;
	}

	public void setGroupName(String groupName)
	{
		this.groupName = groupName;
	}

	/**
	 * 根据Result填充字段
	 * @param rst 填充数据源Result
	 */
	public void fillByResult(Result rst)
	{
		this.setId(Bytes.toString(rst.getRow()));
		this.setUserId(Bytes.toString(rst.getValue(Bytes.toBytes("info"),
				Bytes.toBytes("userid"))));
		this.setFollowId(Bytes.toString(rst.getValue(Bytes.toBytes("info"),
				Bytes.toBytes("followid"))));
		this.setGroupName(Bytes.toString(rst.getValue(Bytes.toBytes("info"),
				Bytes.toBytes("groupname"))));
		this.setRemark(Bytes.toString(rst.getValue(Bytes.toBytes("info"),
				Bytes.toBytes("remark"))));
	}
}
