package org.chingo.gutcom.domain;

// Generated Apr 14, 2013 10:15:06 PM by Hibernate Tools 4.0.0

/**
 * WeiboTopicFollow generated by hbm2java
 */
public class WeiboTopicFollow implements java.io.Serializable
{

	private Long id;
	private WeiboTopic weiboTopic;
	private CommonUser commonUser;

	public WeiboTopicFollow()
	{
	}

	public WeiboTopicFollow(WeiboTopic weiboTopic, CommonUser commonUser)
	{
		this.weiboTopic = weiboTopic;
		this.commonUser = commonUser;
	}

	public Long getId()
	{
		return this.id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	public WeiboTopic getWeiboTopic()
	{
		return this.weiboTopic;
	}

	public void setWeiboTopic(WeiboTopic weiboTopic)
	{
		this.weiboTopic = weiboTopic;
	}

	public CommonUser getCommonUser()
	{
		return this.commonUser;
	}

	public void setCommonUser(CommonUser commonUser)
	{
		this.commonUser = commonUser;
	}

}
