package org.chingo.gutcom.domain;

// Generated Apr 14, 2013 10:15:06 PM by Hibernate Tools 4.0.0

/**
 * WeiboReport generated by hbm2java
 */
public class WeiboReport implements java.io.Serializable
{

	private String rid; // 举报ID
	private String reportUserId; // 举报用户的ID
	private CommonUser reportUser; // 举报用户对象
	private String reportWeiboId; // 举报微博的ID
	private WeiboContent reportWeibo; // 举报微博对象
	private long dateline; // 举报时间戳
	private String reason; // 举报理由
	private byte status; // 举报处理状态

	public WeiboReport()
	{
	}

	public WeiboReport(String rid, String reportUserId, String reportWeiboId,
			long dateline, String reason, byte status)
	{
		this.rid = rid;
		this.reportUserId = reportUserId;
		this.reportWeiboId = reportWeiboId;
		this.dateline = dateline;
		this.reason = reason;
		this.status = status;
	}

	public String getRid()
	{
		return this.rid;
	}

	public void setRid(String rid)
	{
		this.rid = rid;
	}

	public long getDateline()
	{
		return this.dateline;
	}

	public void setDateline(long dateline)
	{
		this.dateline = dateline;
	}

	public String getReason()
	{
		return this.reason;
	}

	public void setReason(String reason)
	{
		this.reason = reason;
	}

	public byte getStatus()
	{
		return this.status;
	}

	public void setStatus(byte status)
	{
		this.status = status;
	}

	public String getReportUserId()
	{
		return reportUserId;
	}

	public void setReportUserId(String reportUserId)
	{
		this.reportUserId = reportUserId;
	}

	public CommonUser getReportUser()
	{
		return reportUser;
	}

	public void setReportUser(CommonUser reportUser)
	{
		this.reportUser = reportUser;
	}

	public String getReportWeiboId()
	{
		return reportWeiboId;
	}

	public void setReportWeiboId(String reportWeiboId)
	{
		this.reportWeiboId = reportWeiboId;
	}

	public WeiboContent getReportWeibo()
	{
		return reportWeibo;
	}

	public void setReportWeibo(WeiboContent reportWeibo)
	{
		this.reportWeibo = reportWeibo;
	}

}
