package org.chingo.gutcom.entity;

// Generated Apr 12, 2013 10:41:18 AM by Hibernate Tools 4.0.0

/**
 * CommonUserProfile generated by hbm2java
 */
public class CommonUserProfile implements java.io.Serializable
{

	private int uid;
	private CommonUser commonUser;
	private String realname;
	private String college;
	private String major;
	private String classname;
	private byte gender;
	private short birthyear;
	private byte birthmonth;
	private byte birthday;
	private String constellation;
	private String zodiac;
	private String bloodtype;
	private String qq;
	private String selfintro;
	private String avatarurl;
	private String bigavatarurl;

	public CommonUserProfile()
	{
	}

	public CommonUserProfile(CommonUser commonUser, String realname,
			String college, String major, String classname, byte gender,
			short birthyear, byte birthmonth, byte birthday,
			String constellation, String zodiac, String bloodtype, String qq,
			String selfintro, String avatarurl, String bigavatarurl)
	{
		this.commonUser = commonUser;
		this.realname = realname;
		this.college = college;
		this.major = major;
		this.classname = classname;
		this.gender = gender;
		this.birthyear = birthyear;
		this.birthmonth = birthmonth;
		this.birthday = birthday;
		this.constellation = constellation;
		this.zodiac = zodiac;
		this.bloodtype = bloodtype;
		this.qq = qq;
		this.selfintro = selfintro;
		this.avatarurl = avatarurl;
		this.bigavatarurl = bigavatarurl;
	}

	public int getUid()
	{
		return this.uid;
	}

	public void setUid(int uid)
	{
		this.uid = uid;
	}

	public CommonUser getCommonUser()
	{
		return this.commonUser;
	}

	public void setCommonUser(CommonUser commonUser)
	{
		this.commonUser = commonUser;
	}

	public String getRealname()
	{
		return this.realname;
	}

	public void setRealname(String realname)
	{
		this.realname = realname;
	}

	public String getCollege()
	{
		return this.college;
	}

	public void setCollege(String college)
	{
		this.college = college;
	}

	public String getMajor()
	{
		return this.major;
	}

	public void setMajor(String major)
	{
		this.major = major;
	}

	public String getClassname()
	{
		return this.classname;
	}

	public void setClassname(String classname)
	{
		this.classname = classname;
	}

	public byte getGender()
	{
		return this.gender;
	}

	public void setGender(byte gender)
	{
		this.gender = gender;
	}

	public short getBirthyear()
	{
		return this.birthyear;
	}

	public void setBirthyear(short birthyear)
	{
		this.birthyear = birthyear;
	}

	public byte getBirthmonth()
	{
		return this.birthmonth;
	}

	public void setBirthmonth(byte birthmonth)
	{
		this.birthmonth = birthmonth;
	}

	public byte getBirthday()
	{
		return this.birthday;
	}

	public void setBirthday(byte birthday)
	{
		this.birthday = birthday;
	}

	public String getConstellation()
	{
		return this.constellation;
	}

	public void setConstellation(String constellation)
	{
		this.constellation = constellation;
	}

	public String getZodiac()
	{
		return this.zodiac;
	}

	public void setZodiac(String zodiac)
	{
		this.zodiac = zodiac;
	}

	public String getBloodtype()
	{
		return this.bloodtype;
	}

	public void setBloodtype(String bloodtype)
	{
		this.bloodtype = bloodtype;
	}

	public String getQq()
	{
		return this.qq;
	}

	public void setQq(String qq)
	{
		this.qq = qq;
	}

	public String getSelfintro()
	{
		return this.selfintro;
	}

	public void setSelfintro(String selfintro)
	{
		this.selfintro = selfintro;
	}

	public String getAvatarurl()
	{
		return this.avatarurl;
	}

	public void setAvatarurl(String avatarurl)
	{
		this.avatarurl = avatarurl;
	}

	public String getBigavatarurl()
	{
		return this.bigavatarurl;
	}

	public void setBigavatarurl(String bigavatarurl)
	{
		this.bigavatarurl = bigavatarurl;
	}

}
