package org.chingo.gutcom.entity;

// Generated Apr 11, 2013 4:11:18 PM by Hibernate Tools 4.0.0

/**
 * CommonMsgRecv generated by hbm2java
 */
public class CommonMsgRecv implements java.io.Serializable
{

	private Long mid;
	private CommonUser commonUserByRecvuser;
	private CommonUser commonUserBySenduser;
	private String content;
	private int dateline;
	private byte isread;

	public CommonMsgRecv()
	{
	}

	public CommonMsgRecv(CommonUser commonUserByRecvuser,
			CommonUser commonUserBySenduser, String content, int dateline,
			byte isread)
	{
		this.commonUserByRecvuser = commonUserByRecvuser;
		this.commonUserBySenduser = commonUserBySenduser;
		this.content = content;
		this.dateline = dateline;
		this.isread = isread;
	}

	public Long getMid()
	{
		return this.mid;
	}

	public void setMid(Long mid)
	{
		this.mid = mid;
	}

	public CommonUser getCommonUserByRecvuser()
	{
		return this.commonUserByRecvuser;
	}

	public void setCommonUserByRecvuser(CommonUser commonUserByRecvuser)
	{
		this.commonUserByRecvuser = commonUserByRecvuser;
	}

	public CommonUser getCommonUserBySenduser()
	{
		return this.commonUserBySenduser;
	}

	public void setCommonUserBySenduser(CommonUser commonUserBySenduser)
	{
		this.commonUserBySenduser = commonUserBySenduser;
	}

	public String getContent()
	{
		return this.content;
	}

	public void setContent(String content)
	{
		this.content = content;
	}

	public int getDateline()
	{
		return this.dateline;
	}

	public void setDateline(int dateline)
	{
		this.dateline = dateline;
	}

	public byte getIsread()
	{
		return this.isread;
	}

	public void setIsread(byte isread)
	{
		this.isread = isread;
	}

}
