package org.chingo.gutcom.entity;

// Generated Apr 12, 2013 10:41:18 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * CommonUser generated by hbm2java
 */
public class CommonUser implements java.io.Serializable
{

	private Integer uid;
	private String nickname;
	private String email;
	private String studentnum;
	private String password;
	private byte status;
	private int regdate;
	private Set<CommonMsgSend> commonMsgSendsForSenduser = new HashSet<CommonMsgSend>(
			0);
	private CommonUserProfile commonUserProfile;
	private Set<CommonMsgSend> commonMsgSendsForRecvuser = new HashSet<CommonMsgSend>(
			0);
	private Set<CommonOplog> commonOplogs = new HashSet<CommonOplog>(0);
	private Set<WeiboContent> weiboContents = new HashSet<WeiboContent>(0);
	private Set<WeiboFollow> weiboFollowsForFollowuid = new HashSet<WeiboFollow>(
			0);
	private Set<ShareReport> shareReports = new HashSet<ShareReport>(0);
	private Set<CommonMsgRecv> commonMsgRecvsForSenduser = new HashSet<CommonMsgRecv>(
			0);
	private Set<CommonSyslog> commonSyslogs = new HashSet<CommonSyslog>(0);
	private Set<WeiboTopic> weiboTopics = new HashSet<WeiboTopic>(0);
	private Set<CommonMsgRecv> commonMsgRecvsForRecvuser = new HashSet<CommonMsgRecv>(
			0);
	private Set<ShareComment> shareComments = new HashSet<ShareComment>(0);
	private Set<WeiboFollow> weiboFollowsForUid = new HashSet<WeiboFollow>(0);
	private Set<WeiboReport> weiboReports = new HashSet<WeiboReport>(0);
	private Set<ShareContent> shareContents = new HashSet<ShareContent>(0);
	private Set<ShareFav> shareFavs = new HashSet<ShareFav>(0);
	private CommonUserStatus commonUserStatus;
	private Set<WeiboFav> weiboFavs = new HashSet<WeiboFav>(0);
	private Set<WeiboAt> weiboAts = new HashSet<WeiboAt>(0);
	private Set<WeiboTopicFollow> weiboTopicFollows = new HashSet<WeiboTopicFollow>(
			0);

	public CommonUser()
	{
	}

	public CommonUser(String nickname, String email, String studentnum,
			String password, byte status, int regdate)
	{
		this.nickname = nickname;
		this.email = email;
		this.studentnum = studentnum;
		this.password = password;
		this.status = status;
		this.regdate = regdate;
	}

	public CommonUser(String nickname, String email, String studentnum,
			String password, byte status, int regdate,
			Set<CommonMsgSend> commonMsgSendsForSenduser,
			CommonUserProfile commonUserProfile,
			Set<CommonMsgSend> commonMsgSendsForRecvuser,
			Set<CommonOplog> commonOplogs, Set<WeiboContent> weiboContents,
			Set<WeiboFollow> weiboFollowsForFollowuid,
			Set<ShareReport> shareReports,
			Set<CommonMsgRecv> commonMsgRecvsForSenduser,
			Set<CommonSyslog> commonSyslogs, Set<WeiboTopic> weiboTopics,
			Set<CommonMsgRecv> commonMsgRecvsForRecvuser,
			Set<ShareComment> shareComments,
			Set<WeiboFollow> weiboFollowsForUid, Set<WeiboReport> weiboReports,
			Set<ShareContent> shareContents, Set<ShareFav> shareFavs,
			CommonUserStatus commonUserStatus, Set<WeiboFav> weiboFavs,
			Set<WeiboAt> weiboAts, Set<WeiboTopicFollow> weiboTopicFollows)
	{
		this.nickname = nickname;
		this.email = email;
		this.studentnum = studentnum;
		this.password = password;
		this.status = status;
		this.regdate = regdate;
		this.commonMsgSendsForSenduser = commonMsgSendsForSenduser;
		this.commonUserProfile = commonUserProfile;
		this.commonMsgSendsForRecvuser = commonMsgSendsForRecvuser;
		this.commonOplogs = commonOplogs;
		this.weiboContents = weiboContents;
		this.weiboFollowsForFollowuid = weiboFollowsForFollowuid;
		this.shareReports = shareReports;
		this.commonMsgRecvsForSenduser = commonMsgRecvsForSenduser;
		this.commonSyslogs = commonSyslogs;
		this.weiboTopics = weiboTopics;
		this.commonMsgRecvsForRecvuser = commonMsgRecvsForRecvuser;
		this.shareComments = shareComments;
		this.weiboFollowsForUid = weiboFollowsForUid;
		this.weiboReports = weiboReports;
		this.shareContents = shareContents;
		this.shareFavs = shareFavs;
		this.commonUserStatus = commonUserStatus;
		this.weiboFavs = weiboFavs;
		this.weiboAts = weiboAts;
		this.weiboTopicFollows = weiboTopicFollows;
	}

	public Integer getUid()
	{
		return this.uid;
	}

	public void setUid(Integer uid)
	{
		this.uid = uid;
	}

	public String getNickname()
	{
		return this.nickname;
	}

	public void setNickname(String nickname)
	{
		this.nickname = nickname;
	}

	public String getEmail()
	{
		return this.email;
	}

	public void setEmail(String email)
	{
		this.email = email;
	}

	public String getStudentnum()
	{
		return this.studentnum;
	}

	public void setStudentnum(String studentnum)
	{
		this.studentnum = studentnum;
	}

	public String getPassword()
	{
		return this.password;
	}

	public void setPassword(String password)
	{
		this.password = password;
	}

	public byte getStatus()
	{
		return this.status;
	}

	public void setStatus(byte status)
	{
		this.status = status;
	}

	public int getRegdate()
	{
		return this.regdate;
	}

	public void setRegdate(int regdate)
	{
		this.regdate = regdate;
	}

	public Set<CommonMsgSend> getCommonMsgSendsForSenduser()
	{
		return this.commonMsgSendsForSenduser;
	}

	public void setCommonMsgSendsForSenduser(
			Set<CommonMsgSend> commonMsgSendsForSenduser)
	{
		this.commonMsgSendsForSenduser = commonMsgSendsForSenduser;
	}

	public CommonUserProfile getCommonUserProfile()
	{
		return this.commonUserProfile;
	}

	public void setCommonUserProfile(CommonUserProfile commonUserProfile)
	{
		this.commonUserProfile = commonUserProfile;
	}

	public Set<CommonMsgSend> getCommonMsgSendsForRecvuser()
	{
		return this.commonMsgSendsForRecvuser;
	}

	public void setCommonMsgSendsForRecvuser(
			Set<CommonMsgSend> commonMsgSendsForRecvuser)
	{
		this.commonMsgSendsForRecvuser = commonMsgSendsForRecvuser;
	}

	public Set<CommonOplog> getCommonOplogs()
	{
		return this.commonOplogs;
	}

	public void setCommonOplogs(Set<CommonOplog> commonOplogs)
	{
		this.commonOplogs = commonOplogs;
	}

	public Set<WeiboContent> getWeiboContents()
	{
		return this.weiboContents;
	}

	public void setWeiboContents(Set<WeiboContent> weiboContents)
	{
		this.weiboContents = weiboContents;
	}

	public Set<WeiboFollow> getWeiboFollowsForFollowuid()
	{
		return this.weiboFollowsForFollowuid;
	}

	public void setWeiboFollowsForFollowuid(
			Set<WeiboFollow> weiboFollowsForFollowuid)
	{
		this.weiboFollowsForFollowuid = weiboFollowsForFollowuid;
	}

	public Set<ShareReport> getShareReports()
	{
		return this.shareReports;
	}

	public void setShareReports(Set<ShareReport> shareReports)
	{
		this.shareReports = shareReports;
	}

	public Set<CommonMsgRecv> getCommonMsgRecvsForSenduser()
	{
		return this.commonMsgRecvsForSenduser;
	}

	public void setCommonMsgRecvsForSenduser(
			Set<CommonMsgRecv> commonMsgRecvsForSenduser)
	{
		this.commonMsgRecvsForSenduser = commonMsgRecvsForSenduser;
	}

	public Set<CommonSyslog> getCommonSyslogs()
	{
		return this.commonSyslogs;
	}

	public void setCommonSyslogs(Set<CommonSyslog> commonSyslogs)
	{
		this.commonSyslogs = commonSyslogs;
	}

	public Set<WeiboTopic> getWeiboTopics()
	{
		return this.weiboTopics;
	}

	public void setWeiboTopics(Set<WeiboTopic> weiboTopics)
	{
		this.weiboTopics = weiboTopics;
	}

	public Set<CommonMsgRecv> getCommonMsgRecvsForRecvuser()
	{
		return this.commonMsgRecvsForRecvuser;
	}

	public void setCommonMsgRecvsForRecvuser(
			Set<CommonMsgRecv> commonMsgRecvsForRecvuser)
	{
		this.commonMsgRecvsForRecvuser = commonMsgRecvsForRecvuser;
	}

	public Set<ShareComment> getShareComments()
	{
		return this.shareComments;
	}

	public void setShareComments(Set<ShareComment> shareComments)
	{
		this.shareComments = shareComments;
	}

	public Set<WeiboFollow> getWeiboFollowsForUid()
	{
		return this.weiboFollowsForUid;
	}

	public void setWeiboFollowsForUid(Set<WeiboFollow> weiboFollowsForUid)
	{
		this.weiboFollowsForUid = weiboFollowsForUid;
	}

	public Set<WeiboReport> getWeiboReports()
	{
		return this.weiboReports;
	}

	public void setWeiboReports(Set<WeiboReport> weiboReports)
	{
		this.weiboReports = weiboReports;
	}

	public Set<ShareContent> getShareContents()
	{
		return this.shareContents;
	}

	public void setShareContents(Set<ShareContent> shareContents)
	{
		this.shareContents = shareContents;
	}

	public Set<ShareFav> getShareFavs()
	{
		return this.shareFavs;
	}

	public void setShareFavs(Set<ShareFav> shareFavs)
	{
		this.shareFavs = shareFavs;
	}

	public CommonUserStatus getCommonUserStatus()
	{
		return this.commonUserStatus;
	}

	public void setCommonUserStatus(CommonUserStatus commonUserStatus)
	{
		this.commonUserStatus = commonUserStatus;
	}

	public Set<WeiboFav> getWeiboFavs()
	{
		return this.weiboFavs;
	}

	public void setWeiboFavs(Set<WeiboFav> weiboFavs)
	{
		this.weiboFavs = weiboFavs;
	}

	public Set<WeiboAt> getWeiboAts()
	{
		return this.weiboAts;
	}

	public void setWeiboAts(Set<WeiboAt> weiboAts)
	{
		this.weiboAts = weiboAts;
	}

	public Set<WeiboTopicFollow> getWeiboTopicFollows()
	{
		return this.weiboTopicFollows;
	}

	public void setWeiboTopicFollows(Set<WeiboTopicFollow> weiboTopicFollows)
	{
		this.weiboTopicFollows = weiboTopicFollows;
	}

}
