package org.chingo.gutcom.entity;

// Generated Apr 11, 2013 4:11:18 PM by Hibernate Tools 4.0.0

/**
 * CommonSysconf generated by hbm2java
 */
public class CommonSysconf implements java.io.Serializable
{

	private Integer cid;
	private String confname;
	private String confvalue;

	public CommonSysconf()
	{
	}

	public CommonSysconf(String confname, String confvalue)
	{
		this.confname = confname;
		this.confvalue = confvalue;
	}

	public Integer getCid()
	{
		return this.cid;
	}

	public void setCid(Integer cid)
	{
		this.cid = cid;
	}

	public String getConfname()
	{
		return this.confname;
	}

	public void setConfname(String confname)
	{
		this.confname = confname;
	}

	public String getConfvalue()
	{
		return this.confvalue;
	}

	public void setConfvalue(String confvalue)
	{
		this.confvalue = confvalue;
	}

}
