package org.chingo.gutcom.entity;

// Generated Apr 12, 2013 9:55:45 AM by Hibernate Tools 4.0.0

/**
 * CommonSyslog generated by hbm2java
 */
public class CommonSyslog implements java.io.Serializable
{

	private Long lid;
	private CommonUser commonUser;
	private String detail;
	private int dateline;

	public CommonSyslog()
	{
	}

	public CommonSyslog(CommonUser commonUser, String detail, int dateline)
	{
		this.commonUser = commonUser;
		this.detail = detail;
		this.dateline = dateline;
	}

	public Long getLid()
	{
		return this.lid;
	}

	public void setLid(Long lid)
	{
		this.lid = lid;
	}

	public CommonUser getCommonUser()
	{
		return this.commonUser;
	}

	public void setCommonUser(CommonUser commonUser)
	{
		this.commonUser = commonUser;
	}

	public String getDetail()
	{
		return this.detail;
	}

	public void setDetail(String detail)
	{
		this.detail = detail;
	}

	public int getDateline()
	{
		return this.dateline;
	}

	public void setDateline(int dateline)
	{
		this.dateline = dateline;
	}

}
