package org.chingo.gutcom.entity;

// Generated Apr 12, 2013 10:41:18 AM by Hibernate Tools 4.0.0

/**
 * CommonSmile generated by hbm2java
 */
public class CommonSmile implements java.io.Serializable
{

	private Integer sid;
	private CommonSmileCategory commonSmileCategory;
	private String description;
	private String imgurl;
	private int order;

	public CommonSmile()
	{
	}

	public CommonSmile(CommonSmileCategory commonSmileCategory,
			String description, String imgurl, int order)
	{
		this.commonSmileCategory = commonSmileCategory;
		this.description = description;
		this.imgurl = imgurl;
		this.order = order;
	}

	public Integer getSid()
	{
		return this.sid;
	}

	public void setSid(Integer sid)
	{
		this.sid = sid;
	}

	public CommonSmileCategory getCommonSmileCategory()
	{
		return this.commonSmileCategory;
	}

	public void setCommonSmileCategory(CommonSmileCategory commonSmileCategory)
	{
		this.commonSmileCategory = commonSmileCategory;
	}

	public String getDescription()
	{
		return this.description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}

	public String getImgurl()
	{
		return this.imgurl;
	}

	public void setImgurl(String imgurl)
	{
		this.imgurl = imgurl;
	}

	public int getOrder()
	{
		return this.order;
	}

	public void setOrder(int order)
	{
		this.order = order;
	}

}
