package org.chingo.gutcom.entity;

// Generated Apr 11, 2013 4:11:18 PM by Hibernate Tools 4.0.0

/**
 * ShareFav generated by hbm2java
 */
public class ShareFav implements java.io.Serializable
{

	private Long fid;
	private ShareContent shareContent;
	private CommonUser commonUser;

	public ShareFav()
	{
	}

	public ShareFav(ShareContent shareContent, CommonUser commonUser)
	{
		this.shareContent = shareContent;
		this.commonUser = commonUser;
	}

	public Long getFid()
	{
		return this.fid;
	}

	public void setFid(Long fid)
	{
		this.fid = fid;
	}

	public ShareContent getShareContent()
	{
		return this.shareContent;
	}

	public void setShareContent(ShareContent shareContent)
	{
		this.shareContent = shareContent;
	}

	public CommonUser getCommonUser()
	{
		return this.commonUser;
	}

	public void setCommonUser(CommonUser commonUser)
	{
		this.commonUser = commonUser;
	}

}
