package org.chingo.gutcom.entity;

// Generated Apr 12, 2013 10:41:18 AM by Hibernate Tools 4.0.0

/**
 * ShareUrl generated by hbm2java
 */
public class ShareUrl implements java.io.Serializable
{

	private Long id;
	private ShareContent shareContent;
	private String url;
	private String description;

	public ShareUrl()
	{
	}

	public ShareUrl(ShareContent shareContent, String url, String description)
	{
		this.shareContent = shareContent;
		this.url = url;
		this.description = description;
	}

	public Long getId()
	{
		return this.id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	public ShareContent getShareContent()
	{
		return this.shareContent;
	}

	public void setShareContent(ShareContent shareContent)
	{
		this.shareContent = shareContent;
	}

	public String getUrl()
	{
		return this.url;
	}

	public void setUrl(String url)
	{
		this.url = url;
	}

	public String getDescription()
	{
		return this.description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}

}
