package org.chingo.gutcom.entity;

// Generated Apr 14, 2013 10:15:06 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * WeiboFollowGroup generated by hbm2java
 */
public class WeiboFollowGroup implements java.io.Serializable
{

	private Integer gid;
	private String groupname;
	private Set<WeiboFollow> weiboFollows = new HashSet<WeiboFollow>(0);

	public WeiboFollowGroup()
	{
	}

	public WeiboFollowGroup(String groupname)
	{
		this.groupname = groupname;
	}

	public WeiboFollowGroup(String groupname, Set<WeiboFollow> weiboFollows)
	{
		this.groupname = groupname;
		this.weiboFollows = weiboFollows;
	}

	public Integer getGid()
	{
		return this.gid;
	}

	public void setGid(Integer gid)
	{
		this.gid = gid;
	}

	public String getGroupname()
	{
		return this.groupname;
	}

	public void setGroupname(String groupname)
	{
		this.groupname = groupname;
	}

	public Set<WeiboFollow> getWeiboFollows()
	{
		return this.weiboFollows;
	}

	public void setWeiboFollows(Set<WeiboFollow> weiboFollows)
	{
		this.weiboFollows = weiboFollows;
	}

}
