package org.chingo.gutcom.entity;

// Generated Apr 11, 2013 4:11:18 PM by Hibernate Tools 4.0.0

/**
 * WeiboFollow generated by hbm2java
 */
public class WeiboFollow implements java.io.Serializable
{

	private Long id;
	private CommonUser commonUserByFollowuid;
	private CommonUser commonUserByUid;
	private int groupid;
	private String remark;

	public WeiboFollow()
	{
	}

	public WeiboFollow(CommonUser commonUserByFollowuid,
			CommonUser commonUserByUid, int groupid, String remark)
	{
		this.commonUserByFollowuid = commonUserByFollowuid;
		this.commonUserByUid = commonUserByUid;
		this.groupid = groupid;
		this.remark = remark;
	}

	public Long getId()
	{
		return this.id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	public CommonUser getCommonUserByFollowuid()
	{
		return this.commonUserByFollowuid;
	}

	public void setCommonUserByFollowuid(CommonUser commonUserByFollowuid)
	{
		this.commonUserByFollowuid = commonUserByFollowuid;
	}

	public CommonUser getCommonUserByUid()
	{
		return this.commonUserByUid;
	}

	public void setCommonUserByUid(CommonUser commonUserByUid)
	{
		this.commonUserByUid = commonUserByUid;
	}

	public int getGroupid()
	{
		return this.groupid;
	}

	public void setGroupid(int groupid)
	{
		this.groupid = groupid;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

}
