package org.chingo.gutcom.entity;

// Generated Apr 12, 2013 9:55:45 AM by Hibernate Tools 4.0.0

/**
 * WeiboFollowGroup generated by hbm2java
 */
public class WeiboFollowGroup implements java.io.Serializable
{

	private Integer gid;
	private String groupname;

	public WeiboFollowGroup()
	{
	}

	public WeiboFollowGroup(String groupname)
	{
		this.groupname = groupname;
	}

	public Integer getGid()
	{
		return this.gid;
	}

	public void setGid(Integer gid)
	{
		this.gid = gid;
	}

	public String getGroupname()
	{
		return this.groupname;
	}

	public void setGroupname(String groupname)
	{
		this.groupname = groupname;
	}

}
